### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by Madlost** [cafeloli/parches-sharin.github.io#2]
Buenas, pues la novela me estaba gustando mucho, pero tras el día de navidad, en la excursión al acuario tras hablar sobre las anguilas, el juego no para de dar un fallo. Cargue varias veces la partida y lo volví a instalar y sigue dando el fallo con una ventana de información con un texto raro.

Las anguilas eléctricas eran geniales.
Sin embargo, acabamos perdiéndonos el espectáculo de los delfines.

Tras eso da siempre el error. Según el bloc de notas es sobre las 18:50:05

**Comment by ConeCafe** [comment]
arreglado en la v7 recien subida hoy
