### ISSUE TITLE
SeaBed

### ISSUE THREAD

**Issue by Esdeath732** [cafeloli/parches-sharin.github.io#4]
En el capítulo 6 en la parte final de la escena de "buceo" después que aparece Takako de pequeña para entrar a la siguiente escena que es "Algo importante" aparece una ventana emergente que no te permite continuar, espero con ansias que lo arreglen ya que me gustó la novela y la traducción.
![sea](https://user-images.githubusercontent.com/104260819/164895603-e00f7634-7745-4907-b910-b05e1163d683.jpg)

**Comment by ConeCafe** [comment]
Subida nueva versión, pero no testeada. Dejo abierto el tema temporalmente para que me digas si se arregló.

**Comment by Esdeath732** [comment]
Hola, lamento la tardanza pero ya lo cheque y si se arregló, muchísimas gracias, espero con ansias tu siguiente proyecto
